[application]
name = "prueba2"

[web.app]
title = "prueba2"
#base_path = "RobotCiudadWeb/develop/experimental/architectury"

[web.watcher]
reload_html = true

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
